### ISSUE TITLE
On about page, refreshing the page breaks it

### ISSUE THREAD

**Issue by kurtisyoung** [andrewscwei/react-static-starter-kit#1]
Not sure if this is an issue with prerendering

**Comment by andrewscwei** [comment]
Is this development only?

**Comment by kurtisyoung** [comment]
Yeah so far. I haven't tested production. Did you see the bug?

**Comment by andrewscwei** [comment]
Yea it only happens in dev cuz the dev server doesn't catch all requests to serve `index.html`. The next change will fix this.
